apiVersion: apps/v1
kind: Deployment
metadata:
  name: Dinosaur-Game-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Dinosaur-Game
  template:
    metadata:
      labels:
        app: Dinosaur-Game
    spec:
      containers:
      - name: Dinosaur-Game-container
        image: ziyadtarek99/Dinosaur-Game:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
